# R Matrix Exercises

Through these exercises we will review the matrix data structure and perhaps introduce you to a few ideas for you to discover on your own! Just answer the questions below written in bold:

**Ex 1: Create 2 vectors A and B, where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() function to create a 2 by 3 matrix from the vectors. You'll need to figure out which of these binding functions is the correct choice.**

In [7]:
A <- c(1,2,3)
B <- c(4,5,6)

C <- cbind(A,B)
print(C)

D <- rbind(A,B)
print(D)    #Correct method

     A B
[1,] 1 4
[2,] 2 5
[3,] 3 6
  [,1] [,2] [,3]
A    1    2    3
B    4    5    6


**Ex 2: Create a 3 by 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow argument in the matrix() function call. Assign this matrix to the variable mat**

In [9]:
mat <- matrix(1:9, nrow = 3)
print(mat)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


**Ex 3: Confirm that mat is a matrix using is.matrix()**

In [10]:
print(is.matrix(mat))

[1] TRUE


**Ex 4: Create a 5 by 5 matrix consisting of the numbers 1-25 and assign it to the variable mat2. The top row should be the numbers 1-5.**

In [15]:
mat2 <- matrix(1:25, nrow=5, byrow=TRUE)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

**Ex 5: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:**

[7,8]

[12,13]

In [21]:
mat2[2,2:3]
mat2[3,2:3]

[1] 7 8

[1] 12 13

**Ex 6: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:**

[19,20]

[24,25]

**Ex 7: What is the sum of all the elements in mat2?**

In [22]:
sum(mat2)

[1] 325

**Ex 8: Ok time for our last exercise! Find out how to use runif() to create a 4 by 5 matrix consisting of 20 random numbers (4*5=20).**

In [34]:
matrix(runif(20, 1, 20), nrow=4)


[,1]      [,2]      [,3]      [,4]      [,5]     
[1,] 12.940007  4.826559 12.886966 19.116712  8.651063
[2,]  3.598669 16.214435  7.035037  7.585986  2.726004
[3,] 10.891945  5.202353  6.588321 14.094363 18.463442
[4,]  1.799835 16.085528  1.449104  4.119863  2.438447